name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      docker-image: ghcr.io/AplinkosMinisterija/biip-zuvinimas-web
      enable-sentry: true
      build-args: |
        NODE_ENV=development
        VITE_SENTRY_DSN=https://0385edf7f78f4ad4a511abae516ae3e8@sentry.biip.lt/7
        VITE_MAPS_HOST=https://dev.maps.biip.lt
