name: Deploy to Production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      docker-image: ghcr.io/AplinkosMinisterija/biip-zuvinimas-web
      enable-sentry: true
      build-args: |
        NODE_ENV=production
        REACT_APP_SENTRY_DSN=https://0385edf7f78f4ad4a511abae516ae3e8@sentry.biip.lt/7
        REACT_APP_MAPS_HOST=https://maps.biip.lt